apiVersion: v1
kind: ConfigMap
metadata:
  name: vscode-editor-configurations
  labels:
     app.kubernetes.io/part-of: che.eclipse.org
     app.kubernetes.io/component: workspaces-config
data:
  configurations.json: |
    {
      "extensions.install-from-vsix-enabled": false
    }
